project:
  type: website
  output-dir: public_build
  render:
    - "*.qmd"
    #- "!som.qmd"
    - "!sandbox/"
    - "!public/"
    - "!hack_code/"
    - "!page_build/"
    - "!files/"
    - "!public_build/"
    - "!archive_code/"
    - "!README.md"
    - "!paper/*/*.qmd"
  resources:
    - source("assets/functions.R")

website:
  title: "SWELTR"
  favicon: "assets/favicon.ico"
  page-footer: "© Copyright 2022 [metacrobe](https://metacrobe.github.io/) & The SWELTR Project. Site constructed using [Quarto](https://quarto.org/)."
  site-url: https://sweltr.github.io/depth/
  repo-url: https://github.com/sweltr/depth/
  repo-actions: [edit, issue]
  page-navigation: true
  bread-crumbs: false
  search:
    location: navbar
    type: overlay
  navbar:
    logo: "assets/icon.png"
    title: false
    background: light
    left:
  #    - text: "Home"
      - icon: home
        href: index.html
      - text: "A. Processing"
        menu:
          - text: "Workflows"
          - text: "---------"
          - text: "1. Cutadapt"
            href: primers.html
          - text: "2. Data Set Prep"
            href: data-prep.html
          - text: "3. Filtering"
            href: filtering.html
      - text: "B. Diversity"
        menu:
          - text: "Workflows"
          - text: "---------"
          - text: "4. Taxonomic"
            href: taxa.html
          - text: "5. Alpha Diversity"
            href: alpha.html
          - text: "6. Beta Diversity"
            href: beta.html
          - text: "7. DA ASVs & Taxa"
            href: da.html
          - text: "8. Metadata"
            href: metadata.html
  #    - icon: fa-code fa-lg
  #      href: raw_code.txt
    right:
      - text: "DATA"
        href: data-availability.html
      - text: PAPER
        href: pub.html
      - text: "SOM"
        href: som.html
      - icon: github
        href: https://github.com/sweltr/depth/
        aria-label: Agua Salud GitHub
      - icon: question
        href: about.html
  sidebar:
      collapse-level: 2
      style: "floating"
      align: left
      contents:
        - section: "A. Processing"
          contents:
            - primers.qmd
            - lotus3_ssu.qmd
            - lotus3_its.qmd
            - lotus3_amf.qmd
            - lotus3_oo.qmd
        - text: "---------"
        - section: "B. Diversity"
          contents:
            - taxa.qmd
            - alpha.qmd
            - beta.qmd
            - da.qmd
            - metadata.qmd
        - section: "More"
          contents:
            - data-availability.qmd
            - som.qmd
            - about.qmd
            - pub.qmd

bibliography: assets/cite.bib
filters:
  - linkate

format:
  html:
    theme: cosmo
    anchor-sections: true
    number-sections: false
    embed-resources: true
    css: assets/css/styles.css
    code-copy: true
    code-link: true
    code-overflow: wrap
    code-fold: false
    code-summary: "Show the code"
    code-tools:
      source: true
      toggle: false
      caption: none
    toc: true
    toc-depth: 3
    toc-expand: 3

    appendix-style: default
    title-block-banner-color: "#FEFEFE"
    title-block-banner: '#113858'
    title-block-style: default
execute:
  freeze: auto
  echo: true
  eval: false
  warning: false
  message: false
  
