project:
  type: website
  output-dir: public_build
  render:
    - "*.qmd"
    #- "!som.qmd"
    - "!sandbox/"
    - "!public/"
    - "!hack_code/"
    - "!page_build/"
    - "!working_files/"
    - "!public_build/"
    - "!archive_code/"
    - "!README.md"
    - "!paper/*/*.qmd"
    - "!test.qmd"
# Finished pages, comment # out to build whole site
    #- "!about.qmd"
    #- "!primers.qmd"
    #- "!lotus3.qmd"
    #- "!curate_ssu.qmd"
    #- "!curate_its.qmd"
    #- "!curate_amf.qmd"
    #- "!curate_oo.qmd"

highlight-style: github

website:
  title: "SWELTR"
  favicon: "assets/favicon.ico"
  page-footer: "© Copyright 2025 [metacrobe](https://metacrobe.github.io/) & The SWELTR Project. Site constructed using [Quarto](https://quarto.org/)."
  site-url: https://sweltr.github.io/depth/
  repo-url: https://github.com/sweltr/depth/
  repo-actions: [edit, issue]
  page-navigation: true
  bread-crumbs: true
  back-to-top-navigation: false  
  search:
    location: navbar
    type: overlay
  navbar:
    logo: "assets/icon.png"
    title: false
    background: light
#    left:
#      - text: "Home"
#      - icon: home
#        href: index.qmd
#      - text: "A. Processing"
#        menu:
#          - text: "Workflows"
#          - text: "---------"
#          - text: "1. Cutadapt"
#            href: primers.qmd
#          - text: "2. Data Set Prep"
#            href: data-prep.qmd
#          - text: "3. Filtering"
#            href: filtering.qmd
#      - text: "B. Diversity"
#        menu:
#          - text: "Workflows"
#          - text: "---------"
#          - text: "4. Taxonomic"
#            href: taxa.qmd
#          - text: "5. Alpha Diversity"
#            href: alpha.qmd
#          - text: "6. Beta Diversity"
#            href: beta.qmd
#          - text: "7. DA ASVs & Taxa"
#            href: da.qmd
#          - text: "8. Metadata"
#            href: metadata.qmd
  #    - icon: fa-code fa-lg
  #      href: raw_code.txt
    right:
#      - text: "DATA"
#        href: data-availability.qmd
#      - text: PAPER
#        href: pub.qmd
#      - text: "SOM"
#        href: som.qmd
      - icon: github
        href: https://github.com/sweltr/depth/
        aria-label: SWELTR Depth
#      - icon: question
#        href: about.qmd
  sidebar:
      collapse-level: 2
      style: "floating"
      align: left
      contents:
        - section: "A. Processing"
          contents:
            - primers.qmd
            - lotus3.qmd
        - section: "B. Data Curation"
          contents:
            - curate_ssu.qmd
            - curate_its.qmd
            - curate_amf.qmd
            - curate_oo.qmd
        - text: "---------"
#        - section: "B. Diversity"
#          contents:
#            - taxa.qmd
#            - alpha.qmd
#            - beta.qmd
#            - da.qmd
#            - metadata.qmd
#        - text: "---------"
#        - section: "More"
#          contents:
#            - data-availability.qmd
#            - som.qmd
#            - about.qmd
#            - pub.qmd

bibliography: assets/cite.bib
filters:
  - linkate

format:
  html:
    #theme: cosmo
    theme:
      light: [cosmo, assets/css/theme.scss]
      dark: [cosmo, assets/css/theme-dark.scss]
    fontsize: 1.1em  
    anchor-sections: true
    number-sections: false
    embed-resources: false
    css: assets/css/styles.css
    code-copy: true
    code-link: true
    code-overflow: wrap
    code-fold: false
    code-summary: "Show the code"
    code-tools:
      source: true
      toggle: false
      caption: none
    toc: true
    toc-depth: 3
    toc-expand: 3
    respect-user-color-scheme: true
    appendix-style: default
    #title-block-banner-color: "#FEFEFE"
    #title-block-banner: '#113858'
    #title-block-style: default
execute:
  freeze: auto
  echo: true
  eval: false
  warning: false
  message: false
  
knitr:
  opts_chunk:
    echo: true
    eval: false
