---
title: "The SWELTR Depth Study"
description: |
  **S**oil **W**arming **E**xperiment in **L**owland **T**ropical **R**ainforest
#author:
#  - name: "Andrew Nottingham"
#    affiliation: University of Edinburgh
#    affiliation-url: https://www.ed.ac.uk/
#  - name: "Jarrod J Scott"
#    orcid: 0000-0001-9863-1318
#    url: https://metacrobe.github.io/
#    affiliation: Smithsonian Tropical Research Institute
#    affiliation-url: https://stri.si.edu/

format:
  html: 
    code-tools: false    
#    css: ["assets/css/styles_index.css", "assets/css/styles.css"]
#title-block-banner: assets/banner.png
---

{{< include include/code/_setup.qmd >}}

## Access to Data & Scripts

Here I provide quick access to data and scripts depending on where you want to start your analysis. I list these in reverse order--beginning with the curated datasets ready for analysis and ending with the raw, unprocessed, fastq data. In each section I provide the relevant data, scripts, and tables. I also link to detailed explanations of each workflow. 

### 4. Processed Data

Data provided here is the output of the [Data Curation](#data-curation) workflows. **These data are ready for analysis**.

::: {.callout-note appearance="default" icon=false}

## Curated Data

| Dataset         | Currated Data (zip files)                                                                      
|-----------------|:---------------------------------------------------------------------------------------------------------------------------------------:|
| 16S rRNA (ssu)  | {{< downloadthis files/SHARE/ssu_curated_data.zip dname="ssu_curated_data" label="ssu_curated_data" icon="download"  type="link" >}}    |
| ITS (its)       | {{< downloadthis files/SHARE/its_curated_data.zip dname="its_curated_data.zip" label="its_curated_data" icon="download" type="link" >}} |
| AMF (amf)       | {{< downloadthis files/SHARE/amf_curated_data.zip dname="amf_curated_data" label="amf_curated_data" icon="download"  type="link" >}}    |
| Oomycete (oo)   | {{< downloadthis files/SHARE/oo_curated_data.zip dname="oo_curated_data.zip" label="oo_curated_data" icon="download" type="link" >}}    |

: Quick links to curated data. {tbl-colwidths="[25,50]"}

These `.zip` files contain the processed data in different formats:

- `xyz_otu_table.txt`: ASV by sample abundance table. 
- `xyz_tax_table.txt`: ASV taxonomic assignments. 
- `xyz_sample_table.txt`: Sample data table, **including read tracking through the entire workflow**.
- `xyz_rep_fasta.fasta`: Representative ASV fasta sequences.

These files each contain all four tables descriped above. 

- `xyz_me_asv.rds`: microtable object from the R [microeco](https://chiliubio.github.io/microeco_tutorial/) package.
- `xyz_ps_asv.rds`: phyloseq object from the R [phyloseq](https://joey711.github.io/phyloseq/) package

Where `xyz` is the root name corresponding to one of the four datasets; **ssu** = 16S rRNA, **its** = ITS, **amf** = Arbuscular mycorrhiza fungi, **oo** = Oomycetes.

:::

#### Curated Data Summary

I strongly encourage anyone interested in these data to look closely at this table--specifically the samples which have been removed at some point in the pipeline. These are represented by `NA` in the table. **This is especially true for the Oomycete dataset**.



::: {.callout-note appearance="default" icon=false}

## Curated Data Summary Table

You can download the table here:


{{< downloadthis files/SHARE/all_samples_final_counts.txt dname=all_samples_final_counts label="Download final read/ASV counts in all datasets" icon=download type=link class=data-button id=all_samples_final_counts >}}

Or view it in-line below. 
:::


{{< include include/code/_summary.qmd >}}


### 3. Data Curation

At this stage fastq files have been [renamed and primers removed](#primer-removal) and [ASVs have been called with LotuS3](#primer-removal). In this workflow I use the phyloseq output from LotuS3 to format the otu, taxonomy, and sample data tables to create a microeco object. Once that is complete I curate the dataset by removing possible contaminants, negative control samples, NA kingdoms, and low-count samples.  

> As of  `r Sys.Date()` I have only done this for the SSU (16S rRNA) dataset. The rest are coming soon. 

Grab this data if you:

a. want to curate the data yourself or   
b. want to see the data before any spurious ASVs or samples were removed. 

::: {.callout-note appearance="default" icon=false}

### {{< fa download >}} &nbsp; phyloseq_ssu.Rdata

{{< downloadthis files/CURATE/phyloseq_ssu.Rdata dname="phyloseq_ssu" label="LotuS3 phyloseq data" icon="code-slash" type="link" >}}

:::


::: {.callout-warning icon=false}

## Workflow

For a more detailed explanation please see the [SSU Data Curation](curate_ssu.qmd) workflow. 

:::


### 2. ASV Inference

Once primer removal is complete you can call ASVs with LotuS3. Here you can find all you need to do this--trimmed fastq files (primers removed), mapping files, and LotuS3 commands. 

{{< include include/data/_lotus3_data_and_scripts.qmd >}}

Once you have the data and mapping files you can run the following commands (assuming you have LotuS3 installed).

```

# SSU dataset
lotus3 -i . -map ssu_miSeqMap.sm.txt -o LOTUS3_ASV -sdmopt sdm_miSeq.txt -p miSeq -amplicon_type SSU  -forwardPrimer GTGCCAGCMGCCGCGGTAA -reversePrimer GGACTACHVGGGTWTCTAAT -clustering dada2 -refDB SLV -taxAligner lambda -threads 20

# ITS dataset
lotus3 -i . -map its_miSeqMap.sm.txt -o LOTUS3_ASV -sdmopt sdm_miSeq_ITS.txt -p miSeq -amplicon_type ITS  -forwardPrimer CTTGGTCATTTAGAGGAAGTAA -reversePrimer GCTGCGTTCTTCATCGATGC -clustering dada2 -refDB lotus3_sh__release_dynamic_s_all_19.02.2025_dev.fasta -tax4refDB lotus3_sh_general_release_dynamic_s_all_19.02.2025_dev.tax -taxAligner lambda -t 20

#AMF dataset
lotus3 -i .-map amf_miSeqMap.sm.txt -o LOTUS3_ASV -sdmopt sdm_miSeq.txt -p miSeq -amplicon_type SSU  -forwardPrimer AAGCTCGTAGTTGAATTTCG -reversePrimer CCCAACTATCCCTATTAATCAT -clustering dada2 -refDB SLV -taxAligner lambda -t 20

# Oomycete dataset
lotus3 -i . -map oo_miSeqMap.sm.txt -o LOTUS3_ASV -sdmopt sdm_miSeq_ITS.txt -p miSeq -amplicon_type ITS -forwardPrimer GGAAGGATCATTACCACA -reversePrimer GCTGCGTTCTTCATCGATGC -clustering dada2 -refDB lotus3_sh_general_release_dynamic_s_all_19.02.2025_dev.fasta -tax4refDB lotus3_sh_general_release_dynamic_s_all_19.02.2025_dev.tax -taxAligner lambda -t 20


```

::: {.callout-warning icon=false}

## Workflow

For a more detailed explanation please see the [ASV Inference](lotus3.qmd) workflow. 

:::


### 1. Primer Removal

Want to start at the very beginning? Here are the raw fastq files, fastq renaming script, rename tables, and cutadapt primer removal scripts. 

{{< include include/data/_raw_data_and_scripts.qmd >}}

</br>

::: {.callout-note appearance="default" icon=false}

### {{< fa download >}} &nbsp; rename.sh

{{< downloadthis files/RENAME/rename.sh dname="rename" label="Bash script to rename samples" icon="code-slash" type="link" >}}

:::

Steps to reproduce results:

a. Run the  script `rename.sh` to rename the fastq files. For example, to change the names of the fastq files in the SSU dataset, simply run the following:

```{bash}
#| eval: false
#| echo: true
bash rename.sh SSU fastq files/ ssu_rename.txt
```

b. Run the cutadapt script (e.g., `1_cut_ssu.R`) using the renamed fastq file directory. 

```{bash}
Rscript 1_cut_ssu.R
```

::: {.callout-warning icon=false}

## Workflow

For a more detailed explanation please see the [Primer Removal](primers.qmd) workflow. 

:::

{{< include include/code/_footer.qmd >}}
